repositories {
        maven {
            url = "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

dependencies {
  modImplementation "curse.maven:photon-871522:7381162"
  modImplementation "curse.maven:ldlib-626676:7412415"
}


repositories {
  maven {
    name = "Illusive Soulworks maven"
    url = "https://maven.theillusivec4.top/"
  }
}

dependencies {
  modImplementation "top.theillusivec4.curios:curios-forge:5.14.1+1.20.1"
}


