/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.noirsmp.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.noirsmp.item.*;
import net.mcreator.noirsmp.NoirSmpMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class NoirSmpModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, NoirSmpMod.MODID);
	public static final RegistryObject<Item> MANOPLA_DE_SLIME;
	public static final RegistryObject<Item> DADO_FEURAL;
	public static final RegistryObject<Item> LAMINA_DO_ARAUTO_PLUMIFERO;
	public static final RegistryObject<Item> SINO_DE_MARFIM_SPEED;
	public static final RegistryObject<Item> SINO_DE_MARFIM_REGEN;
	public static final RegistryObject<Item> SINO_DE_MARFIM_STRENGTH;
	public static final RegistryObject<Item> SINO_DE_MARFIM_SLOW_FALLING;
	public static final RegistryObject<Item> SINO_DE_MARFIM_NIGHT_VISION;
	public static final RegistryObject<Item> SINO_DE_MARFIM_JUMP_BOOST;
	public static final RegistryObject<Item> SINO_DE_MARFIM_INVISIBILITY;
	public static final RegistryObject<Item> SINO_DE_MARFIM_RESISTENCE;
	public static final RegistryObject<Item> SINO_DE_MARFIM_AQUATIC_RESPIRATION;
	public static final RegistryObject<Item> MANOPLA_DA_CALAMIDADE;
	public static final RegistryObject<Item> PASSOS_ETERIOS_BOOTS;
	public static final RegistryObject<Item> LEVIATAN;
	public static final RegistryObject<Item> DOPPEL_MASK;
	public static final RegistryObject<Item> AGULHA_DOS_PESADELOS_PROFUNDOS;
	public static final RegistryObject<Item> BENGALA;
	public static final RegistryObject<Item> CANO_DE_METAL;
	public static final RegistryObject<Item> ESPETO;
	public static final RegistryObject<Item> MARRETA;
	public static final RegistryObject<Item> NINJATO;
	public static final RegistryObject<Item> ESPADA;
	public static final RegistryObject<Item> PEDRA;
	public static final RegistryObject<Item> SLIME_MACE;
	public static final RegistryObject<Item> RIPA;
	public static final RegistryObject<Item> ROLO;
	public static final RegistryObject<Item> TACO_COM_ARAME;
	public static final RegistryObject<Item> MOLOTOV;
	public static final RegistryObject<Item> TIJOLO;
	public static final RegistryObject<Item> MARRETA_GRAVITACIONAL;
	public static final RegistryObject<Item> ARMA_DE_BURACO_NEGRO;
	public static final RegistryObject<Item> UMBRAVEU;
	public static final RegistryObject<Item> SINGULARIS_ITEM;
	public static final RegistryObject<Item> EGIDE_PRISMATICA;
	public static final RegistryObject<Item> MEDALHAO_DO_PARASITA;
	public static final RegistryObject<Item> FRAGMENTO_DO_CAOS;
	public static final RegistryObject<Item> CORACAO_CONGELADO;
	public static final RegistryObject<Item> AMULETO_DA_AGILIDADE;
	public static final RegistryObject<Item> SINTETIC_LOG;
	public static final RegistryObject<Item> SINTETIC_WOOD;
	public static final RegistryObject<Item> STRIPPED_SINTETIC_LOG;
	public static final RegistryObject<Item> STRIPPED_SINTETIC_WOOD;
	public static final RegistryObject<Item> SINTETIC_PLANKS;
	public static final RegistryObject<Item> SINTETIC_LEAVES;
	public static final RegistryObject<Item> SINTETIC_STAIRS;
	public static final RegistryObject<Item> SINTETIC_SLAB;
	public static final RegistryObject<Item> SINTETIC_FENCE;
	public static final RegistryObject<Item> SINTETIC_FENCE_GATE;
	public static final RegistryObject<Item> SINTETIC_DOOR;
	public static final RegistryObject<Item> SINTETIC_TRAPDOOR;
	public static final RegistryObject<Item> SINTETIC_PRESSURE_PLATE;
	public static final RegistryObject<Item> SINTETIC_BUTTON;
	public static final RegistryObject<Item> AETHERION;
	public static final RegistryObject<Item> AETHERION_ORE;
	public static final RegistryObject<Item> AETHERION_BLOCK;
	public static final RegistryObject<Item> AETHERION_PICKAXE;
	public static final RegistryObject<Item> AETHERION_AXE;
	public static final RegistryObject<Item> AETHERION_SWORD;
	public static final RegistryObject<Item> AETHERION_SHOVEL;
	public static final RegistryObject<Item> AETHERION_HOE;
	public static final RegistryObject<Item> AETHERION_ARMOR_HELMET;
	public static final RegistryObject<Item> AETHERION_ARMOR_CHESTPLATE;
	public static final RegistryObject<Item> AETHERION_ARMOR_LEGGINGS;
	public static final RegistryObject<Item> AETHERION_ARMOR_BOOTS;
	public static final RegistryObject<Item> GRAMETITA;
	public static final RegistryObject<Item> ESTRETION;
	public static final RegistryObject<Item> ESTELITA;
	public static final RegistryObject<Item> CRIOGER_BUCKET;
	public static final RegistryObject<Item> ARBOREA_LOG;
	public static final RegistryObject<Item> ARBOREA_WOOD;
	public static final RegistryObject<Item> STRIPPED_ARBOREA_LOG;
	public static final RegistryObject<Item> STRIPPED_ARBOREA_WOOD;
	public static final RegistryObject<Item> ARBOREA_PLANKS;
	public static final RegistryObject<Item> ARBOREA_LEAVES;
	public static final RegistryObject<Item> ARBOREA_STAIRS;
	public static final RegistryObject<Item> ARBOREA_SLAB;
	public static final RegistryObject<Item> ARBOREA_FENCE;
	public static final RegistryObject<Item> ARBOREA_FENCE_GATE;
	public static final RegistryObject<Item> ARBOREA_DOOR;
	public static final RegistryObject<Item> ARBOREA_TRAPDOOR;
	public static final RegistryObject<Item> ARBOREA_PRESSURE_PLATE;
	public static final RegistryObject<Item> ARBOREA_BUTTON;
	public static final RegistryObject<Item> ANEL_DO_TITA;
	public static final RegistryObject<Item> EMBLEMA_DO_GUERREIRO;
	public static final RegistryObject<Item> FRAGMENTO_PRISMATICO;
	public static final RegistryObject<Item> CRONOTITA_INGOT;
	public static final RegistryObject<Item> CRONOTITA_ORE;
	public static final RegistryObject<Item> CRONOTITA_BLOCK;
	public static final RegistryObject<Item> CRONOTITA_PICKAXE;
	public static final RegistryObject<Item> CRONOTITA_AXE;
	public static final RegistryObject<Item> CRONOTITA_SWORD;
	public static final RegistryObject<Item> CRONOTITA_SHOVEL;
	public static final RegistryObject<Item> CRONOTITA_HOE;
	public static final RegistryObject<Item> CRONOTITA_ARMOR_HELMET;
	public static final RegistryObject<Item> CRONOTITA_ARMOR_CHESTPLATE;
	public static final RegistryObject<Item> CRONOTITA_ARMOR_LEGGINGS;
	public static final RegistryObject<Item> CRONOTITA_ARMOR_BOOTS;
	public static final RegistryObject<Item> ETER_DUST;
	public static final RegistryObject<Item> ETER_ORE;
	public static final RegistryObject<Item> ETER_BLOCK;
	public static final RegistryObject<Item> ETER_PICKAXE;
	public static final RegistryObject<Item> ETER_AXE;
	public static final RegistryObject<Item> ETER_SWORD;
	public static final RegistryObject<Item> ETER_SHOVEL;
	public static final RegistryObject<Item> ETER_HOE;
	public static final RegistryObject<Item> ETER_ARMOR_HELMET;
	public static final RegistryObject<Item> ETER_ARMOR_CHESTPLATE;
	public static final RegistryObject<Item> ETER_ARMOR_LEGGINGS;
	public static final RegistryObject<Item> ETER_ARMOR_BOOTS;
	public static final RegistryObject<Item> FRACTALITA;
	public static final RegistryObject<Item> TESSERACTITA;
	public static final RegistryObject<Item> NEBULITA;
	public static final RegistryObject<Item> ESTELITA_STAIRS;
	public static final RegistryObject<Item> ESTELITA_SLAB;
	public static final RegistryObject<Item> ESTELITA_PRESSURE_PLATE;
	public static final RegistryObject<Item> ESTELITA_BUTTON;
	public static final RegistryObject<Item> ESTELITA_WALL;
	public static final RegistryObject<Item> FRACTALITA_STAIRS;
	public static final RegistryObject<Item> FRACTALITA_SLAB;
	public static final RegistryObject<Item> FRACTALITA_PRESSURE_PLATE;
	public static final RegistryObject<Item> FRACTALITA_BUTTON;
	public static final RegistryObject<Item> FRACTALITA_WALL;
	public static final RegistryObject<Item> TESSERACTITA_STAIRS;
	public static final RegistryObject<Item> TESSERACTITA_SLAB;
	public static final RegistryObject<Item> TESSERACTITA_PRESSURE_PLATE;
	public static final RegistryObject<Item> TESSERACTITA_BUTTON;
	public static final RegistryObject<Item> TESSERACTITA_WALL;
	public static final RegistryObject<Item> LITOMORPH;
	public static final RegistryObject<Item> LITOMORPH_STAIRS;
	public static final RegistryObject<Item> LITOMORPH_SLAB;
	public static final RegistryObject<Item> LITOMORPH_PRESSURE_PLATE;
	public static final RegistryObject<Item> LITOMORPH_BUTTON;
	public static final RegistryObject<Item> LITOMORPH_WALL;
	public static final RegistryObject<Item> PULSE_LOG;
	public static final RegistryObject<Item> PULSE_WOOD;
	public static final RegistryObject<Item> STRIPPED_PULSE_LOG;
	public static final RegistryObject<Item> STRIPPED_PULSE_WOOD;
	public static final RegistryObject<Item> PULSE_PLANKS;
	public static final RegistryObject<Item> PULSE_LEAVES;
	public static final RegistryObject<Item> PULSE_STAIRS;
	public static final RegistryObject<Item> PULSE_SLAB;
	public static final RegistryObject<Item> PULSE_FENCE;
	public static final RegistryObject<Item> PULSE_FENCE_GATE;
	public static final RegistryObject<Item> PULSE_DOOR;
	public static final RegistryObject<Item> PULSE_TRAPDOOR;
	public static final RegistryObject<Item> PULSE_PRESSURE_PLATE;
	public static final RegistryObject<Item> PULSE_BUTTON;
	public static final RegistryObject<Item> GALINHA_INVERTIDA_SPAWN_EGG;
	public static final RegistryObject<Item> VACA_INVERTIDA_SPAWN_EGG;
	public static final RegistryObject<Item> RAPOSA_INVERTIDA_SPAWN_EGG;
	public static final RegistryObject<Item> CABRA_INVERTIDA_SPAWN_EGG;
	public static final RegistryObject<Item> PORCO_INVERTIDO_SPAWN_EGG;
	public static final RegistryObject<Item> ZUMBI_INVERTIDO_SPAWN_EGG;
	public static final RegistryObject<Item> ESQUELETO_INVERTIDO_SPAWN_EGG;
	public static final RegistryObject<Item> SELO_DO_MARTIR;
	public static final RegistryObject<Item> RELOGIO_DA_VIOLENCIA;
	public static final RegistryObject<Item> OLHO_DO_EXECUTOR;
	public static final RegistryObject<Item> QUEBRA_MUNDOS;
	public static final RegistryObject<Item> NOIR_BLOCK;
	public static final RegistryObject<Item> MARCA_DO_CARNICEIRO;
	public static final RegistryObject<Item> TOTEM_DA_CACADA;
	public static final RegistryObject<Item> MASCARA_DA_RAPOSA;
	public static final RegistryObject<Item> SINTETIC_SAPLING;
	public static final RegistryObject<Item> ARBOREA_SAPLING;
	public static final RegistryObject<Item> PULSE_SAPLING;
	public static final RegistryObject<Item> MACA_INSTAVEL;
	static {
		MANOPLA_DE_SLIME = REGISTRY.register("manopla_de_slime", ManoplaDeSlimeItem::new);
		DADO_FEURAL = REGISTRY.register("dado_feural", DadoFeuralItem::new);
		LAMINA_DO_ARAUTO_PLUMIFERO = REGISTRY.register("lamina_do_arauto_plumifero", LaminaDoArautoPlumiferoItem::new);
		SINO_DE_MARFIM_SPEED = REGISTRY.register("sino_de_marfim_speed", SinoDeMarfimSpeedItem::new);
		SINO_DE_MARFIM_REGEN = REGISTRY.register("sino_de_marfim_regen", SinoDeMarfimRegenItem::new);
		SINO_DE_MARFIM_STRENGTH = REGISTRY.register("sino_de_marfim_strength", SinoDeMarfimStrengthItem::new);
		SINO_DE_MARFIM_SLOW_FALLING = REGISTRY.register("sino_de_marfim_slow_falling", SinoDeMarfimSlowFallingItem::new);
		SINO_DE_MARFIM_NIGHT_VISION = REGISTRY.register("sino_de_marfim_night_vision", SinoDeMarfimNightVisionItem::new);
		SINO_DE_MARFIM_JUMP_BOOST = REGISTRY.register("sino_de_marfim_jump_boost", SinoDeMarfimJumpBoostItem::new);
		SINO_DE_MARFIM_INVISIBILITY = REGISTRY.register("sino_de_marfim_invisibility", SinoDeMarfimInvisibilityItem::new);
		SINO_DE_MARFIM_RESISTENCE = REGISTRY.register("sino_de_marfim_resistence", SinoDeMarfimResistenceItem::new);
		SINO_DE_MARFIM_AQUATIC_RESPIRATION = REGISTRY.register("sino_de_marfim_aquatic_respiration", SinoDeMarfimAquaticRespirationItem::new);
		MANOPLA_DA_CALAMIDADE = REGISTRY.register("manopla_da_calamidade", ManoplaDaCalamidadeItem::new);
		PASSOS_ETERIOS_BOOTS = REGISTRY.register("passos_eterios_boots", PassosEteriosItem.Boots::new);
		LEVIATAN = REGISTRY.register("leviatan", LeviatanItem::new);
		DOPPEL_MASK = REGISTRY.register("doppel_mask", DoppelMaskItem::new);
		AGULHA_DOS_PESADELOS_PROFUNDOS = REGISTRY.register("agulha_dos_pesadelos_profundos", AgulhaDosPesadelosProfundosItem::new);
		BENGALA = REGISTRY.register("bengala", BengalaItem::new);
		CANO_DE_METAL = REGISTRY.register("cano_de_metal", CanoDeMetalItem::new);
		ESPETO = REGISTRY.register("espeto", EspetoItem::new);
		MARRETA = REGISTRY.register("marreta", MarretaItem::new);
		NINJATO = REGISTRY.register("ninjato", NinjatoItem::new);
		ESPADA = REGISTRY.register("espada", ESPADAItem::new);
		PEDRA = REGISTRY.register("pedra", PEDRAItem::new);
		SLIME_MACE = REGISTRY.register("slime_mace", SlimeMaceItem::new);
		RIPA = REGISTRY.register("ripa", RipaItem::new);
		ROLO = REGISTRY.register("rolo", RoloItem::new);
		TACO_COM_ARAME = REGISTRY.register("taco_com_arame", TacoComArameItem::new);
		MOLOTOV = REGISTRY.register("molotov", MolotovItem::new);
		TIJOLO = REGISTRY.register("tijolo", TijoloItem::new);
		MARRETA_GRAVITACIONAL = REGISTRY.register("marreta_gravitacional", MarretaGravitacionalItem::new);
		ARMA_DE_BURACO_NEGRO = REGISTRY.register("arma_de_buraco_negro", ArmaDeBuracoNegroItem::new);
		UMBRAVEU = REGISTRY.register("umbraveu", UmbraveuItem::new);
		SINGULARIS_ITEM = REGISTRY.register("singularis_item", SingularisItemItem::new);
		EGIDE_PRISMATICA = REGISTRY.register("egide_prismatica", EgidePrismaticaItem::new);
		MEDALHAO_DO_PARASITA = REGISTRY.register("medalhao_do_parasita", MedalhaoDoParasitaItem::new);
		FRAGMENTO_DO_CAOS = REGISTRY.register("fragmento_do_caos", FragmentoDoCaosItem::new);
		CORACAO_CONGELADO = REGISTRY.register("coracao_congelado", CoracaoCongeladoItem::new);
		AMULETO_DA_AGILIDADE = REGISTRY.register("amuleto_da_agilidade", AmuletoDaAgilidadeItem::new);
		SINTETIC_LOG = block(NoirSmpModBlocks.SINTETIC_LOG);
		SINTETIC_WOOD = block(NoirSmpModBlocks.SINTETIC_WOOD);
		STRIPPED_SINTETIC_LOG = block(NoirSmpModBlocks.STRIPPED_SINTETIC_LOG);
		STRIPPED_SINTETIC_WOOD = block(NoirSmpModBlocks.STRIPPED_SINTETIC_WOOD);
		SINTETIC_PLANKS = block(NoirSmpModBlocks.SINTETIC_PLANKS);
		SINTETIC_LEAVES = block(NoirSmpModBlocks.SINTETIC_LEAVES);
		SINTETIC_STAIRS = block(NoirSmpModBlocks.SINTETIC_STAIRS);
		SINTETIC_SLAB = block(NoirSmpModBlocks.SINTETIC_SLAB);
		SINTETIC_FENCE = block(NoirSmpModBlocks.SINTETIC_FENCE);
		SINTETIC_FENCE_GATE = block(NoirSmpModBlocks.SINTETIC_FENCE_GATE);
		SINTETIC_DOOR = doubleBlock(NoirSmpModBlocks.SINTETIC_DOOR);
		SINTETIC_TRAPDOOR = block(NoirSmpModBlocks.SINTETIC_TRAPDOOR);
		SINTETIC_PRESSURE_PLATE = block(NoirSmpModBlocks.SINTETIC_PRESSURE_PLATE);
		SINTETIC_BUTTON = block(NoirSmpModBlocks.SINTETIC_BUTTON);
		AETHERION = REGISTRY.register("aetherion", AetherionItem::new);
		AETHERION_ORE = block(NoirSmpModBlocks.AETHERION_ORE);
		AETHERION_BLOCK = block(NoirSmpModBlocks.AETHERION_BLOCK);
		AETHERION_PICKAXE = REGISTRY.register("aetherion_pickaxe", AetherionPickaxeItem::new);
		AETHERION_AXE = REGISTRY.register("aetherion_axe", AetherionAxeItem::new);
		AETHERION_SWORD = REGISTRY.register("aetherion_sword", AetherionSwordItem::new);
		AETHERION_SHOVEL = REGISTRY.register("aetherion_shovel", AetherionShovelItem::new);
		AETHERION_HOE = REGISTRY.register("aetherion_hoe", AetherionHoeItem::new);
		AETHERION_ARMOR_HELMET = REGISTRY.register("aetherion_armor_helmet", AetherionArmorItem.Helmet::new);
		AETHERION_ARMOR_CHESTPLATE = REGISTRY.register("aetherion_armor_chestplate", AetherionArmorItem.Chestplate::new);
		AETHERION_ARMOR_LEGGINGS = REGISTRY.register("aetherion_armor_leggings", AetherionArmorItem.Leggings::new);
		AETHERION_ARMOR_BOOTS = REGISTRY.register("aetherion_armor_boots", AetherionArmorItem.Boots::new);
		GRAMETITA = block(NoirSmpModBlocks.GRAMETITA);
		ESTRETION = block(NoirSmpModBlocks.ESTRETION);
		ESTELITA = block(NoirSmpModBlocks.ESTELITA);
		CRIOGER_BUCKET = REGISTRY.register("crioger_bucket", DistorcedFluidItem::new);
		ARBOREA_LOG = block(NoirSmpModBlocks.ARBOREA_LOG);
		ARBOREA_WOOD = block(NoirSmpModBlocks.ARBOREA_WOOD);
		STRIPPED_ARBOREA_LOG = block(NoirSmpModBlocks.STRIPPED_ARBOREA_LOG);
		STRIPPED_ARBOREA_WOOD = block(NoirSmpModBlocks.STRIPPED_ARBOREA_WOOD);
		ARBOREA_PLANKS = block(NoirSmpModBlocks.ARBOREA_PLANKS);
		ARBOREA_LEAVES = block(NoirSmpModBlocks.ARBOREA_LEAVES);
		ARBOREA_STAIRS = block(NoirSmpModBlocks.ARBOREA_STAIRS);
		ARBOREA_SLAB = block(NoirSmpModBlocks.ARBOREA_SLAB);
		ARBOREA_FENCE = block(NoirSmpModBlocks.ARBOREA_FENCE);
		ARBOREA_FENCE_GATE = block(NoirSmpModBlocks.ARBOREA_FENCE_GATE);
		ARBOREA_DOOR = doubleBlock(NoirSmpModBlocks.ARBOREA_DOOR);
		ARBOREA_TRAPDOOR = block(NoirSmpModBlocks.ARBOREA_TRAPDOOR);
		ARBOREA_PRESSURE_PLATE = block(NoirSmpModBlocks.ARBOREA_PRESSURE_PLATE);
		ARBOREA_BUTTON = block(NoirSmpModBlocks.ARBOREA_BUTTON);
		ANEL_DO_TITA = REGISTRY.register("anel_do_tita", AnelDoTitaItem::new);
		EMBLEMA_DO_GUERREIRO = REGISTRY.register("emblema_do_guerreiro", EmblemaDoGuerreiroItem::new);
		FRAGMENTO_PRISMATICO = REGISTRY.register("fragmento_prismatico", FragmentoPrismaticoItem::new);
		CRONOTITA_INGOT = REGISTRY.register("cronotita_ingot", CronotitaIngotItem::new);
		CRONOTITA_ORE = block(NoirSmpModBlocks.CRONOTITA_ORE);
		CRONOTITA_BLOCK = block(NoirSmpModBlocks.CRONOTITA_BLOCK);
		CRONOTITA_PICKAXE = REGISTRY.register("cronotita_pickaxe", CronotitaPickaxeItem::new);
		CRONOTITA_AXE = REGISTRY.register("cronotita_axe", CronotitaAxeItem::new);
		CRONOTITA_SWORD = REGISTRY.register("cronotita_sword", CronotitaSwordItem::new);
		CRONOTITA_SHOVEL = REGISTRY.register("cronotita_shovel", CronotitaShovelItem::new);
		CRONOTITA_HOE = REGISTRY.register("cronotita_hoe", CronotitaHoeItem::new);
		CRONOTITA_ARMOR_HELMET = REGISTRY.register("cronotita_armor_helmet", CronotitaArmorItem.Helmet::new);
		CRONOTITA_ARMOR_CHESTPLATE = REGISTRY.register("cronotita_armor_chestplate", CronotitaArmorItem.Chestplate::new);
		CRONOTITA_ARMOR_LEGGINGS = REGISTRY.register("cronotita_armor_leggings", CronotitaArmorItem.Leggings::new);
		CRONOTITA_ARMOR_BOOTS = REGISTRY.register("cronotita_armor_boots", CronotitaArmorItem.Boots::new);
		ETER_DUST = REGISTRY.register("eter_dust", EterDustItem::new);
		ETER_ORE = block(NoirSmpModBlocks.ETER_ORE);
		ETER_BLOCK = block(NoirSmpModBlocks.ETER_BLOCK);
		ETER_PICKAXE = REGISTRY.register("eter_pickaxe", EterPickaxeItem::new);
		ETER_AXE = REGISTRY.register("eter_axe", EterAxeItem::new);
		ETER_SWORD = REGISTRY.register("eter_sword", EterSwordItem::new);
		ETER_SHOVEL = REGISTRY.register("eter_shovel", EterShovelItem::new);
		ETER_HOE = REGISTRY.register("eter_hoe", EterHoeItem::new);
		ETER_ARMOR_HELMET = REGISTRY.register("eter_armor_helmet", EterArmorItem.Helmet::new);
		ETER_ARMOR_CHESTPLATE = REGISTRY.register("eter_armor_chestplate", EterArmorItem.Chestplate::new);
		ETER_ARMOR_LEGGINGS = REGISTRY.register("eter_armor_leggings", EterArmorItem.Leggings::new);
		ETER_ARMOR_BOOTS = REGISTRY.register("eter_armor_boots", EterArmorItem.Boots::new);
		FRACTALITA = block(NoirSmpModBlocks.FRACTALITA);
		TESSERACTITA = block(NoirSmpModBlocks.TESSERACTITA);
		NEBULITA = block(NoirSmpModBlocks.NEBULITA);
		ESTELITA_STAIRS = block(NoirSmpModBlocks.ESTELITA_STAIRS);
		ESTELITA_SLAB = block(NoirSmpModBlocks.ESTELITA_SLAB);
		ESTELITA_PRESSURE_PLATE = block(NoirSmpModBlocks.ESTELITA_PRESSURE_PLATE);
		ESTELITA_BUTTON = block(NoirSmpModBlocks.ESTELITA_BUTTON);
		ESTELITA_WALL = block(NoirSmpModBlocks.ESTELITA_WALL);
		FRACTALITA_STAIRS = block(NoirSmpModBlocks.FRACTALITA_STAIRS);
		FRACTALITA_SLAB = block(NoirSmpModBlocks.FRACTALITA_SLAB);
		FRACTALITA_PRESSURE_PLATE = block(NoirSmpModBlocks.FRACTALITA_PRESSURE_PLATE);
		FRACTALITA_BUTTON = block(NoirSmpModBlocks.FRACTALITA_BUTTON);
		FRACTALITA_WALL = block(NoirSmpModBlocks.FRACTALITA_WALL);
		TESSERACTITA_STAIRS = block(NoirSmpModBlocks.TESSERACTITA_STAIRS);
		TESSERACTITA_SLAB = block(NoirSmpModBlocks.TESSERACTITA_SLAB);
		TESSERACTITA_PRESSURE_PLATE = block(NoirSmpModBlocks.TESSERACTITA_PRESSURE_PLATE);
		TESSERACTITA_BUTTON = block(NoirSmpModBlocks.TESSERACTITA_BUTTON);
		TESSERACTITA_WALL = block(NoirSmpModBlocks.TESSERACTITA_WALL);
		LITOMORPH = block(NoirSmpModBlocks.LITOMORPH);
		LITOMORPH_STAIRS = block(NoirSmpModBlocks.LITOMORPH_STAIRS);
		LITOMORPH_SLAB = block(NoirSmpModBlocks.LITOMORPH_SLAB);
		LITOMORPH_PRESSURE_PLATE = block(NoirSmpModBlocks.LITOMORPH_PRESSURE_PLATE);
		LITOMORPH_BUTTON = block(NoirSmpModBlocks.LITOMORPH_BUTTON);
		LITOMORPH_WALL = block(NoirSmpModBlocks.LITOMORPH_WALL);
		PULSE_LOG = block(NoirSmpModBlocks.PULSE_LOG);
		PULSE_WOOD = block(NoirSmpModBlocks.PULSE_WOOD);
		STRIPPED_PULSE_LOG = block(NoirSmpModBlocks.STRIPPED_PULSE_LOG);
		STRIPPED_PULSE_WOOD = block(NoirSmpModBlocks.STRIPPED_PULSE_WOOD);
		PULSE_PLANKS = block(NoirSmpModBlocks.PULSE_PLANKS);
		PULSE_LEAVES = block(NoirSmpModBlocks.PULSE_LEAVES);
		PULSE_STAIRS = block(NoirSmpModBlocks.PULSE_STAIRS);
		PULSE_SLAB = block(NoirSmpModBlocks.PULSE_SLAB);
		PULSE_FENCE = block(NoirSmpModBlocks.PULSE_FENCE);
		PULSE_FENCE_GATE = block(NoirSmpModBlocks.PULSE_FENCE_GATE);
		PULSE_DOOR = doubleBlock(NoirSmpModBlocks.PULSE_DOOR);
		PULSE_TRAPDOOR = block(NoirSmpModBlocks.PULSE_TRAPDOOR);
		PULSE_PRESSURE_PLATE = block(NoirSmpModBlocks.PULSE_PRESSURE_PLATE);
		PULSE_BUTTON = block(NoirSmpModBlocks.PULSE_BUTTON);
		GALINHA_INVERTIDA_SPAWN_EGG = REGISTRY.register("galinha_invertida_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.GALINHA_INVERTIDA, -16711681, -16763905, new Item.Properties()));
		VACA_INVERTIDA_SPAWN_EGG = REGISTRY.register("vaca_invertida_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.VACA_INVERTIDA, -16724788, -16777012, new Item.Properties()));
		RAPOSA_INVERTIDA_SPAWN_EGG = REGISTRY.register("raposa_invertida_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.RAPOSA_INVERTIDA, -16724788, -16776961, new Item.Properties()));
		CABRA_INVERTIDA_SPAWN_EGG = REGISTRY.register("cabra_invertida_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.CABRA_INVERTIDA, -13421569, -16737844, new Item.Properties()));
		PORCO_INVERTIDO_SPAWN_EGG = REGISTRY.register("porco_invertido_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.PORCO_INVERTIDO, -6684673, -16763905, new Item.Properties()));
		ZUMBI_INVERTIDO_SPAWN_EGG = REGISTRY.register("zumbi_invertido_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.ZUMBI_INVERTIDO, -16737895, -10066177, new Item.Properties()));
		ESQUELETO_INVERTIDO_SPAWN_EGG = REGISTRY.register("esqueleto_invertido_spawn_egg", () -> new ForgeSpawnEggItem(NoirSmpModEntities.ESQUELETO_INVERTIDO, -3342337, -16777063, new Item.Properties()));
		SELO_DO_MARTIR = REGISTRY.register("selo_do_martir", SeloDoMartirItem::new);
		RELOGIO_DA_VIOLENCIA = REGISTRY.register("relogio_da_violencia", RelogioDaViolenciaItem::new);
		OLHO_DO_EXECUTOR = REGISTRY.register("olho_do_executor", OlhoDoExecutorItem::new);
		QUEBRA_MUNDOS = REGISTRY.register("quebra_mundos", QuebraMundosItem::new);
		NOIR_BLOCK = block(NoirSmpModBlocks.NOIR_BLOCK, new Item.Properties().fireResistant());
		MARCA_DO_CARNICEIRO = REGISTRY.register("marca_do_carniceiro", MarcaDoCarniceiroItem::new);
		TOTEM_DA_CACADA = REGISTRY.register("totem_da_cacada", TotemDaCacadaItem::new);
		MASCARA_DA_RAPOSA = REGISTRY.register("mascara_da_raposa", MascaraDaRaposaItem::new);
		SINTETIC_SAPLING = block(NoirSmpModBlocks.SINTETIC_SAPLING);
		ARBOREA_SAPLING = block(NoirSmpModBlocks.ARBOREA_SAPLING);
		PULSE_SAPLING = block(NoirSmpModBlocks.PULSE_SAPLING);
		MACA_INSTAVEL = REGISTRY.register("maca_instavel", MacaInstavelItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}

	@SubscribeEvent
	@OnlyIn(Dist.CLIENT)
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(EGIDE_PRISMATICA.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
		});
	}
}