/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.noirsmp.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.noirsmp.block.*;
import net.mcreator.noirsmp.NoirSmpMod;

public class NoirSmpModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, NoirSmpMod.MODID);
	public static final RegistryObject<Block> PROJETO_ZERO_PORTAL;
	public static final RegistryObject<Block> SINTETIC_LOG;
	public static final RegistryObject<Block> SINTETIC_WOOD;
	public static final RegistryObject<Block> STRIPPED_SINTETIC_LOG;
	public static final RegistryObject<Block> STRIPPED_SINTETIC_WOOD;
	public static final RegistryObject<Block> SINTETIC_PLANKS;
	public static final RegistryObject<Block> SINTETIC_LEAVES;
	public static final RegistryObject<Block> SINTETIC_STAIRS;
	public static final RegistryObject<Block> SINTETIC_SLAB;
	public static final RegistryObject<Block> SINTETIC_FENCE;
	public static final RegistryObject<Block> SINTETIC_FENCE_GATE;
	public static final RegistryObject<Block> SINTETIC_DOOR;
	public static final RegistryObject<Block> SINTETIC_TRAPDOOR;
	public static final RegistryObject<Block> SINTETIC_PRESSURE_PLATE;
	public static final RegistryObject<Block> SINTETIC_BUTTON;
	public static final RegistryObject<Block> AETHERION_ORE;
	public static final RegistryObject<Block> AETHERION_BLOCK;
	public static final RegistryObject<Block> GRAMETITA;
	public static final RegistryObject<Block> ESTRETION;
	public static final RegistryObject<Block> ESTELITA;
	public static final RegistryObject<Block> CRIOGER;
	public static final RegistryObject<Block> ARBOREA_LOG;
	public static final RegistryObject<Block> ARBOREA_WOOD;
	public static final RegistryObject<Block> STRIPPED_ARBOREA_LOG;
	public static final RegistryObject<Block> STRIPPED_ARBOREA_WOOD;
	public static final RegistryObject<Block> ARBOREA_PLANKS;
	public static final RegistryObject<Block> ARBOREA_LEAVES;
	public static final RegistryObject<Block> ARBOREA_STAIRS;
	public static final RegistryObject<Block> ARBOREA_SLAB;
	public static final RegistryObject<Block> ARBOREA_FENCE;
	public static final RegistryObject<Block> ARBOREA_FENCE_GATE;
	public static final RegistryObject<Block> ARBOREA_DOOR;
	public static final RegistryObject<Block> ARBOREA_TRAPDOOR;
	public static final RegistryObject<Block> ARBOREA_PRESSURE_PLATE;
	public static final RegistryObject<Block> ARBOREA_BUTTON;
	public static final RegistryObject<Block> CRONOTITA_ORE;
	public static final RegistryObject<Block> CRONOTITA_BLOCK;
	public static final RegistryObject<Block> ETER_ORE;
	public static final RegistryObject<Block> ETER_BLOCK;
	public static final RegistryObject<Block> FRACTALITA;
	public static final RegistryObject<Block> TESSERACTITA;
	public static final RegistryObject<Block> NEBULITA;
	public static final RegistryObject<Block> ESTELITA_STAIRS;
	public static final RegistryObject<Block> ESTELITA_SLAB;
	public static final RegistryObject<Block> ESTELITA_PRESSURE_PLATE;
	public static final RegistryObject<Block> ESTELITA_BUTTON;
	public static final RegistryObject<Block> ESTELITA_WALL;
	public static final RegistryObject<Block> FRACTALITA_STAIRS;
	public static final RegistryObject<Block> FRACTALITA_SLAB;
	public static final RegistryObject<Block> FRACTALITA_PRESSURE_PLATE;
	public static final RegistryObject<Block> FRACTALITA_BUTTON;
	public static final RegistryObject<Block> FRACTALITA_WALL;
	public static final RegistryObject<Block> TESSERACTITA_STAIRS;
	public static final RegistryObject<Block> TESSERACTITA_SLAB;
	public static final RegistryObject<Block> TESSERACTITA_PRESSURE_PLATE;
	public static final RegistryObject<Block> TESSERACTITA_BUTTON;
	public static final RegistryObject<Block> TESSERACTITA_WALL;
	public static final RegistryObject<Block> LITOMORPH;
	public static final RegistryObject<Block> LITOMORPH_STAIRS;
	public static final RegistryObject<Block> LITOMORPH_SLAB;
	public static final RegistryObject<Block> LITOMORPH_PRESSURE_PLATE;
	public static final RegistryObject<Block> LITOMORPH_BUTTON;
	public static final RegistryObject<Block> LITOMORPH_WALL;
	public static final RegistryObject<Block> PULSE_LOG;
	public static final RegistryObject<Block> PULSE_WOOD;
	public static final RegistryObject<Block> STRIPPED_PULSE_LOG;
	public static final RegistryObject<Block> STRIPPED_PULSE_WOOD;
	public static final RegistryObject<Block> PULSE_PLANKS;
	public static final RegistryObject<Block> PULSE_LEAVES;
	public static final RegistryObject<Block> PULSE_STAIRS;
	public static final RegistryObject<Block> PULSE_SLAB;
	public static final RegistryObject<Block> PULSE_FENCE;
	public static final RegistryObject<Block> PULSE_FENCE_GATE;
	public static final RegistryObject<Block> PULSE_DOOR;
	public static final RegistryObject<Block> PULSE_TRAPDOOR;
	public static final RegistryObject<Block> PULSE_PRESSURE_PLATE;
	public static final RegistryObject<Block> PULSE_BUTTON;
	public static final RegistryObject<Block> NOIR_BLOCK;
	public static final RegistryObject<Block> SINTETIC_SAPLING;
	public static final RegistryObject<Block> ARBOREA_SAPLING;
	public static final RegistryObject<Block> PULSE_SAPLING;
	static {
		PROJETO_ZERO_PORTAL = REGISTRY.register("projeto_zero_portal", ProjetoZeroPortalBlock::new);
		SINTETIC_LOG = REGISTRY.register("sintetic_log", SinteticLogBlock::new);
		SINTETIC_WOOD = REGISTRY.register("sintetic_wood", SinteticWoodBlock::new);
		STRIPPED_SINTETIC_LOG = REGISTRY.register("stripped_sintetic_log", StrippedSinteticLogBlock::new);
		STRIPPED_SINTETIC_WOOD = REGISTRY.register("stripped_sintetic_wood", StrippedSinteticWoodBlock::new);
		SINTETIC_PLANKS = REGISTRY.register("sintetic_planks", SinteticPlanksBlock::new);
		SINTETIC_LEAVES = REGISTRY.register("sintetic_leaves", SinteticLeavesBlock::new);
		SINTETIC_STAIRS = REGISTRY.register("sintetic_stairs", SinteticStairsBlock::new);
		SINTETIC_SLAB = REGISTRY.register("sintetic_slab", SinteticSlabBlock::new);
		SINTETIC_FENCE = REGISTRY.register("sintetic_fence", SinteticFenceBlock::new);
		SINTETIC_FENCE_GATE = REGISTRY.register("sintetic_fence_gate", SinteticFenceGateBlock::new);
		SINTETIC_DOOR = REGISTRY.register("sintetic_door", SinteticDoorBlock::new);
		SINTETIC_TRAPDOOR = REGISTRY.register("sintetic_trapdoor", SinteticTrapdoorBlock::new);
		SINTETIC_PRESSURE_PLATE = REGISTRY.register("sintetic_pressure_plate", SinteticPressurePlateBlock::new);
		SINTETIC_BUTTON = REGISTRY.register("sintetic_button", SinteticButtonBlock::new);
		AETHERION_ORE = REGISTRY.register("aetherion_ore", AetherionOreBlock::new);
		AETHERION_BLOCK = REGISTRY.register("aetherion_block", AetherionBlockBlock::new);
		GRAMETITA = REGISTRY.register("grametita", Dimensao000GramaBlock::new);
		ESTRETION = REGISTRY.register("estretion", Dimensao000TerraBlock::new);
		ESTELITA = REGISTRY.register("estelita", PedraDistorcidaBlock::new);
		CRIOGER = REGISTRY.register("crioger", DistorcedFluidBlock::new);
		ARBOREA_LOG = REGISTRY.register("arborea_log", ArboreaLogBlock::new);
		ARBOREA_WOOD = REGISTRY.register("arborea_wood", ArboreaWoodBlock::new);
		STRIPPED_ARBOREA_LOG = REGISTRY.register("stripped_arborea_log", StrippedArboreaLogBlock::new);
		STRIPPED_ARBOREA_WOOD = REGISTRY.register("stripped_arborea_wood", StrippedArboreaWoodBlock::new);
		ARBOREA_PLANKS = REGISTRY.register("arborea_planks", ArboreaPlanksBlock::new);
		ARBOREA_LEAVES = REGISTRY.register("arborea_leaves", ArboreaLeavesBlock::new);
		ARBOREA_STAIRS = REGISTRY.register("arborea_stairs", ArboreaStairsBlock::new);
		ARBOREA_SLAB = REGISTRY.register("arborea_slab", ArboreaSlabBlock::new);
		ARBOREA_FENCE = REGISTRY.register("arborea_fence", ArboreaFenceBlock::new);
		ARBOREA_FENCE_GATE = REGISTRY.register("arborea_fence_gate", ArboreaFenceGateBlock::new);
		ARBOREA_DOOR = REGISTRY.register("arborea_door", ArboreaDoorBlock::new);
		ARBOREA_TRAPDOOR = REGISTRY.register("arborea_trapdoor", ArboreaTrapdoorBlock::new);
		ARBOREA_PRESSURE_PLATE = REGISTRY.register("arborea_pressure_plate", ArboreaPressurePlateBlock::new);
		ARBOREA_BUTTON = REGISTRY.register("arborea_button", ArboreaButtonBlock::new);
		CRONOTITA_ORE = REGISTRY.register("cronotita_ore", CronotitaOreBlock::new);
		CRONOTITA_BLOCK = REGISTRY.register("cronotita_block", CronotitaBlockBlock::new);
		ETER_ORE = REGISTRY.register("eter_ore", EterOreBlock::new);
		ETER_BLOCK = REGISTRY.register("eter_block", EterBlockBlock::new);
		FRACTALITA = REGISTRY.register("fractalita", FractalitaBlock::new);
		TESSERACTITA = REGISTRY.register("tesseractita", TesseractitaBlock::new);
		NEBULITA = REGISTRY.register("nebulita", NebulitaBlock::new);
		ESTELITA_STAIRS = REGISTRY.register("estelita_stairs", EstelitaStairsBlock::new);
		ESTELITA_SLAB = REGISTRY.register("estelita_slab", EstelitaSlabBlock::new);
		ESTELITA_PRESSURE_PLATE = REGISTRY.register("estelita_pressure_plate", EstelitaPressurePlateBlock::new);
		ESTELITA_BUTTON = REGISTRY.register("estelita_button", EstelitaButtonBlock::new);
		ESTELITA_WALL = REGISTRY.register("estelita_wall", EstelitaWallBlock::new);
		FRACTALITA_STAIRS = REGISTRY.register("fractalita_stairs", FractalitaStairsBlock::new);
		FRACTALITA_SLAB = REGISTRY.register("fractalita_slab", FractalitaSlabBlock::new);
		FRACTALITA_PRESSURE_PLATE = REGISTRY.register("fractalita_pressure_plate", FractalitaPressurePlateBlock::new);
		FRACTALITA_BUTTON = REGISTRY.register("fractalita_button", FractalitaButtonBlock::new);
		FRACTALITA_WALL = REGISTRY.register("fractalita_wall", FractalitaWallBlock::new);
		TESSERACTITA_STAIRS = REGISTRY.register("tesseractita_stairs", TesseractitaStairsBlock::new);
		TESSERACTITA_SLAB = REGISTRY.register("tesseractita_slab", TesseractitaSlabBlock::new);
		TESSERACTITA_PRESSURE_PLATE = REGISTRY.register("tesseractita_pressure_plate", TesseractitaPressurePlateBlock::new);
		TESSERACTITA_BUTTON = REGISTRY.register("tesseractita_button", TesseractitaButtonBlock::new);
		TESSERACTITA_WALL = REGISTRY.register("tesseractita_wall", TesseractitaWallBlock::new);
		LITOMORPH = REGISTRY.register("litomorph", LitomorphBlock::new);
		LITOMORPH_STAIRS = REGISTRY.register("litomorph_stairs", LitomorphStairsBlock::new);
		LITOMORPH_SLAB = REGISTRY.register("litomorph_slab", LitomorphSlabBlock::new);
		LITOMORPH_PRESSURE_PLATE = REGISTRY.register("litomorph_pressure_plate", LitomorphPressurePlateBlock::new);
		LITOMORPH_BUTTON = REGISTRY.register("litomorph_button", LitomorphButtonBlock::new);
		LITOMORPH_WALL = REGISTRY.register("litomorph_wall", LitomorphWallBlock::new);
		PULSE_LOG = REGISTRY.register("pulse_log", PulseLogBlock::new);
		PULSE_WOOD = REGISTRY.register("pulse_wood", PulseWoodBlock::new);
		STRIPPED_PULSE_LOG = REGISTRY.register("stripped_pulse_log", StrippedPulseLogBlock::new);
		STRIPPED_PULSE_WOOD = REGISTRY.register("stripped_pulse_wood", StrippedPulseWoodBlock::new);
		PULSE_PLANKS = REGISTRY.register("pulse_planks", PulsePlanksBlock::new);
		PULSE_LEAVES = REGISTRY.register("pulse_leaves", PulseLeavesBlock::new);
		PULSE_STAIRS = REGISTRY.register("pulse_stairs", PulseStairsBlock::new);
		PULSE_SLAB = REGISTRY.register("pulse_slab", PulseSlabBlock::new);
		PULSE_FENCE = REGISTRY.register("pulse_fence", PulseFenceBlock::new);
		PULSE_FENCE_GATE = REGISTRY.register("pulse_fence_gate", PulseFenceGateBlock::new);
		PULSE_DOOR = REGISTRY.register("pulse_door", PulseDoorBlock::new);
		PULSE_TRAPDOOR = REGISTRY.register("pulse_trapdoor", PulseTrapdoorBlock::new);
		PULSE_PRESSURE_PLATE = REGISTRY.register("pulse_pressure_plate", PulsePressurePlateBlock::new);
		PULSE_BUTTON = REGISTRY.register("pulse_button", PulseButtonBlock::new);
		NOIR_BLOCK = REGISTRY.register("noir_block", NOIRBlockBlock::new);
		SINTETIC_SAPLING = REGISTRY.register("sintetic_sapling", SinteticSaplingBlock::new);
		ARBOREA_SAPLING = REGISTRY.register("arborea_sapling", ArboreaSaplingBlock::new);
		PULSE_SAPLING = REGISTRY.register("pulse_sapling", PulseSaplingBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}